export default {
  id: "mammouth",
  priority: 25,
  alias: "mammouth",
  uiAlias: "mammouth",
  display: {
    name: "Mammouth AI",
    icon: "neurology",
    color: "#9F6C45",
    textIcon: "MM",
    website: "https://mammouth.ai",
    notice: {
      text: "OpenAI-compatible aggregator (Claude, GPT, Gemini, GLM, Kimi, Qwen…). Subscriptions include monthly API credits; usage and cost are tracked per API key.",
      apiKeyUrl: "https://mammouth.ai/app/account/settings/api",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.mammouth.ai/v1/chat/completions",
    validateUrl: "https://api.mammouth.ai/v1/models",
    thinkingFormat: "openai",
    // LiteLLM proxy: GET /key/info returns this key's spend / max_budget.
    usage: {
      url: "https://api.mammouth.ai/key/info",
    },
  },
  // Static fallback from the published model table (info.mammouth.ai/docs/api-quick-start).
  // The live list from GET /v1/models (modelsFetcher below) replaces these when a
  // key is configured, so new/retired models track the account automatically.
  models: [
    { id: "mammouth-recommended", name: "Mammouth Recommended (auto pick)" },
    { id: "claude-fable-5.1", name: "Claude Fable 5.1" },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5" },
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "gemini-3.1-flash-image-preview", name: "Gemini 3.1 Flash Image (preview)" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro (preview)" },
    { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash" },
    { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash" },
    { id: "glm-5.3", name: "GLM 5.3" },
    { id: "glm-5.3-flash", name: "GLM 5.3 Flash" },
    { id: "gpt-5.4", name: "GPT 5.4" },
    { id: "gpt-5.4-mini", name: "GPT 5.4 Mini" },
    { id: "gpt-5.4-nano", name: "GPT 5.4 Nano" },
    { id: "gpt-5.5", name: "GPT 5.5" },
    { id: "gpt-5.6-luna", name: "GPT 5.6 Luna" },
    { id: "gpt-5.6-sol", name: "GPT 5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT 5.6 Terra" },
    { id: "gpt-6-astra", name: "GPT 6 Astra" },
    { id: "grok-4.6", name: "Grok 4.6" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "llama-4-maverick", name: "Llama 4 Maverick" },
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "mistral-medium-3-5", name: "Mistral Medium 3.5" },
    { id: "mistral-small-3.2-24b-instruct", name: "Mistral Small 3.2 24B" },
    { id: "qwen3.7-plus", name: "Qwen 3.7 Plus" },
    { id: "qwen3.8-flash", name: "Qwen 3.8 Flash" },
    { id: "sonar-deep-research", name: "Sonar Deep Research" },
    { id: "sonar-pro", name: "Sonar Pro" },
    { id: "text-embedding-3-large", name: "Text Embedding 3 Large", kind: "embedding" },
    { id: "text-embedding-3-small", name: "Text Embedding 3 Small", kind: "embedding" },
  ],
  // Account-scoped live list (requires the key): tracks plan changes and new models.
  modelsFetcher: { url: "https://api.mammouth.ai/v1/models", type: "openai", auth: "bearer" },
  passthroughModels: true,
  embeddingConfig: {
    baseUrl: "https://api.mammouth.ai/v1/embeddings",
    authType: "apikey",
    authHeader: "bearer",
  },
  serviceKinds: ["llm", "embedding"],
  features: {
    usage: true,
    usageApikey: true,
  },
};
